### ISSUE TITLE
Notification

### ISSUE THREAD

**Issue by sdkyron** [Serubin/pulse-sms-web#160]
I'm not getting any notification with the desktop pulse sms, i have the same issue with the firefox plugin if that makes any difference.

**Comment by Serubin** [comment]
Hi, Unfortunately this is no longer the upstream for the web version of PulseSMS. I wish I could help you but the new owners have completely closed sourced this project. You can find their contact info under "Help and Feedback" in the app or at their twitter https://twitter.com/pulsesms 

Sorry I can't be of more help.

**Comment by sdkyron** [comment]
I understand that but i still have the issue with the desktop version...

**Comment by Serubin** [comment]
All versions of pulse are now managed by MapleMedia. The desktop version is just a wrapper for the webversion so all the info I gave you earlier applies. Please contact MapleMedia they now own pulse.

https://twitter.com/pulsesms

**Comment by sdkyron** [comment]
Alright i will contact them, thank you :)
