### ISSUE TITLE
websocket messages has null "from" field

### ISSUE THREAD

**Issue by treethought** [Serubin/pulse-sms-web#161]
Not sure if there is a better place for this issue, but the when streaming websocket messages, the `added_message` operation payloads always have `message.content.from` set to null.

Is it expected to contain the sender of the message? There doesn't seem to be any special handling/retrieval of the from value aside from [assigning it to message_from](https://github.com/Serubin/pulse-sms-web/blob/master/src/utils/api/stream.js#L102)

**Comment by Serubin** [comment]
Hi, Unfortunately this is no longer the upstream for the web version of PulseSMS. I wish I could help you but the new owners have completely closed sourced this project. You can find their contact info under "Help and Feedback" in the app or at their twitter https://twitter.com/pulsesms 

Sorry I can't be of more help.

**Comment by treethought** [comment]
I see, thanks for the reply and your work on this version.
