### ISSUE TITLE
Web App Does Not Sync

### ISSUE THREAD

**Issue by sgtcoder** [Serubin/pulse-sms-web#163]
OS: Windows 10/Ubuntu 20
Pulse Version: Web/4.3.0

Between the Android App and the Web App the Deleted Threads don't remove and the Archived threads don't sync properly. I believe I resolved this in the past by resetting and resyncing everything, but that's not an ideal solution.

**Comment by tokenwizard** [comment]
I'm having similar issues. When I sign into the Web App, I see all my current messages that are also on my Phone, but when I type a reply on the Web App and hit send, it just sits there and says "Sending..." forever. If I refresh the page it no longer says Sending and looks like it sent, but it never actually goes through to the other party and never shows up in the Conversation on my Phone.

**Comment by Serubin** [comment]
Please report any issues to twitter.com/pulsesms

This repo is no longer affiliated with maplemedia
